openapi: 3.0.3
info:
  title: GESTION DE PROJET - BUG
  version: 1.0.0

servers:
  - url: http://localhost:5000
  - https://gestion-de-projet-bug.onrender.com

tags:
  - name: Auth
  - name: Projects
  - name: Bugs

paths:

  ########################
  # 🔐 AUTHENTIFICATION #
  ########################

  /api/auth/register:
    post:
      tags: [Auth]
      summary: Inscription d'un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Utilisateur inscrit
        "400":
          description: Email déjà utilisé
        "500":
          description: Erreur serveur

  /api/auth/login:
    post:
      tags: [Auth]
      summary: Connexion d'un utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Connexion réussie
        "401":
          description: Identifiants invalides
        "500":
          description: Erreur serveur

  /api/auth/me:
    get:
      tags: [Auth]
      summary: Récupérer l'utilisateur courant
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Données utilisateur
        "401":
          description: Non autorisé

  ########################
  # 📁 PROJETS           #
  ########################

  /api/projects:
    post:
      tags: [Projects]
      summary: Créer un projet
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, type]
              properties:
                name:
                  type: string
                type:
                  type: string
      responses:
        "201":
          description: Projet créé
        "403":
          description: Limite atteinte
        "500":
          description: Erreur serveur

    get:
      tags: [Projects]
      summary: Obtenir tous les projets de l'utilisateur
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Liste des projets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        "401":
          description: Non autorisé
        "500":
          description: Erreur serveur

  /api/projects/summary:
    get:
      tags: [Projects]
      summary: Obtenir les détails complet des projets et leurs bugs
      security:
        - bearerAuth: []
      parameters:
        - name: projectId
          in: query
          schema:
            type: string
        - name: withBugs
          in: query
          schema:
            type: boolean
      responses:
        "200":
          description: Résumé projet+bugs
          content:
            application/json:
              schema:
                type: object
                properties:
                  projects:
                    type: array
                    items:
                      $ref: "#/components/schemas/Project"
                  bugs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Bug"

  ######################
  # 🐛 BUGS             #
  ######################

  /api/bugs/{projectId}:
    post:
      tags: [Bugs]
      summary: Créer un bug pour un projet donné
      security:
        - bearerAuth: []
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BugInput"
      responses:
        "201":
          description: Bug créé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Bug"
        "403":
          description: Accès interdit au projet
        "404":
          description: Projet non trouvé
        "500":
          description: Erreur serveur

  /api/bugs:
    get:
      tags: [Bugs]
      summary: Obtenir tous les bugs (filtres, pagination)
      security:
        - bearerAuth: []
      parameters:
        - name: projectId
          in: query
          schema:
            type: string
        - name: type
          in: query
          schema:
            type: string
            enum: ["log", "error", "warning", "info"]
        - name: status
          in: query
          schema:
            type: string
            enum: ["en cours", "terminée", "supprimée"]
        - name: from
          in: query
          schema:
            type: string
            format: date
        - name: to
          in: query
          schema:
            type: string
            format: date
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Liste des bugs filtrée
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer
                  bugs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Bug"
        "500":
          description: Erreur serveur

  /api/bugs/{bugId}:
    get:
      tags: [Bugs]
      summary: Détails complets d’un bug (avec projet et utilisateur)
      security:
        - bearerAuth: []
      parameters:
        - name: bugId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Détail complet
          content:
            application/json:
              schema:
                type: object
                properties:
                  bug:
                    $ref: "#/components/schemas/Bug"
                  project:
                    $ref: "#/components/schemas/Project"
                  user:
                    $ref: "#/components/schemas/User"
        "403":
          description: Non autorisé
        "404":
          description: Bug ou projet non trouvé
        "500":
          description: Erreur serveur

    delete:
      tags: [Bugs]
      summary: Supprimer un bug existant
      security:
        - bearerAuth: []
      parameters:
        - name: bugId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Bug supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bug supprimé avec succès
        "403":
          description: Non autorisé
        "404":
          description: Bug non trouvé
        "500":
          description: Erreur serveur


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    BugInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "Erreur d'affichage"
        description:
          type: string
          example: "Le bouton ne s'affiche pas en responsive"
        type:
          type: string
          enum: ["log", "error", "warning", "info"]
          example: error
        status:
          type: string
          enum: ["en cours", "terminée", "supprimée"]
          example: en cours

    Bug:
      allOf:
        - $ref: "#/components/schemas/BugInput"
        - type: object
          properties:
            _id:
              type: string
            projectId:
              type: string
            userId:
              type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time

    Project:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        type:
          type: string
        CountBug:
          type: integer

    User:
      type: object
      properties:
        _id:
          type: string
        email:
          type: string
